// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bloodheaven/audit/v1/report.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity is how much attention a finding deserves.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	// SEVERITY_INFO — worth knowing, nothing is wrong.
	Severity_SEVERITY_INFO Severity = 1
	// SEVERITY_WARNING — a real problem that is not breaking anything yet.
	Severity_SEVERITY_WARNING Severity = 2
	// SEVERITY_BLOCKER — already broken, or already exploitable. Deliberately rare:
	// a false blocker is the most expensive mistake this product can make.
	Severity_SEVERITY_BLOCKER Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_BLOCKER",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_BLOCKER":     3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_bloodheaven_audit_v1_report_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_bloodheaven_audit_v1_report_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{0}
}

// Category answers "what kind of trouble is this", not "how bad is it".
type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	// CATEGORY_CONFLICT — two things claim the same resource: a name, a port, a path.
	Category_CATEGORY_CONFLICT Category = 1
	// CATEGORY_RESOURCE — capacity: memory, disk, inodes, lookup budgets.
	Category_CATEGORY_RESOURCE Category = 2
	// CATEGORY_SECURITY — an exposure somebody could act on.
	Category_CATEGORY_SECURITY Category = 3
	// CATEGORY_EXPIRY — something with a date on it that is running out.
	Category_CATEGORY_EXPIRY Category = 4
	// CATEGORY_MISSING — an expected safeguard that is not configured at all.
	Category_CATEGORY_MISSING Category = 5
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_CONFLICT",
		2: "CATEGORY_RESOURCE",
		3: "CATEGORY_SECURITY",
		4: "CATEGORY_EXPIRY",
		5: "CATEGORY_MISSING",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_CONFLICT":    1,
		"CATEGORY_RESOURCE":    2,
		"CATEGORY_SECURITY":    3,
		"CATEGORY_EXPIRY":      4,
		"CATEGORY_MISSING":     5,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_bloodheaven_audit_v1_report_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_bloodheaven_audit_v1_report_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{1}
}

// Confidence states where false positives are possible. Anything inferred from a
// fingerprint, a third-party index, or a parse of free-form text is at most MEDIUM.
type Confidence int32

const (
	Confidence_CONFIDENCE_UNSPECIFIED Confidence = 0
	Confidence_CONFIDENCE_LOW         Confidence = 1
	Confidence_CONFIDENCE_MEDIUM      Confidence = 2
	Confidence_CONFIDENCE_HIGH        Confidence = 3
)

// Enum value maps for Confidence.
var (
	Confidence_name = map[int32]string{
		0: "CONFIDENCE_UNSPECIFIED",
		1: "CONFIDENCE_LOW",
		2: "CONFIDENCE_MEDIUM",
		3: "CONFIDENCE_HIGH",
	}
	Confidence_value = map[string]int32{
		"CONFIDENCE_UNSPECIFIED": 0,
		"CONFIDENCE_LOW":         1,
		"CONFIDENCE_MEDIUM":      2,
		"CONFIDENCE_HIGH":        3,
	}
)

func (x Confidence) Enum() *Confidence {
	p := new(Confidence)
	*p = x
	return p
}

func (x Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_bloodheaven_audit_v1_report_proto_enumTypes[2].Descriptor()
}

func (Confidence) Type() protoreflect.EnumType {
	return &file_bloodheaven_audit_v1_report_proto_enumTypes[2]
}

func (x Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confidence.Descriptor instead.
func (Confidence) EnumDescriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{2}
}

// CollectorStatus is the outcome of one check.
type CollectorStatus int32

const (
	CollectorStatus_COLLECTOR_STATUS_UNSPECIFIED CollectorStatus = 0
	CollectorStatus_COLLECTOR_STATUS_OK          CollectorStatus = 1
	CollectorStatus_COLLECTOR_STATUS_FAILED      CollectorStatus = 2
	CollectorStatus_COLLECTOR_STATUS_TIMEOUT     CollectorStatus = 3
	// COLLECTOR_STATUS_SKIPPED — the check never ran: switched off, not authorised
	// for this level, or its input was unavailable. The note says which.
	CollectorStatus_COLLECTOR_STATUS_SKIPPED CollectorStatus = 4
	// COLLECTOR_STATUS_PARTIAL — the check ran and produced usable results, but not
	// all of them: something it wanted to read was unreachable, or a bound it declares
	// was reached. The note says what is missing.
	//
	// This is not a shade of OK. A producer whose check covers several probes — a
	// whole section of a host audit, say — has a real state that neither OK nor FAILED
	// describes, and collapsing it into OK loses the one thing the reader most needs to
	// know: that the absence of findings here is not evidence of their absence.
	CollectorStatus_COLLECTOR_STATUS_PARTIAL CollectorStatus = 5
)

// Enum value maps for CollectorStatus.
var (
	CollectorStatus_name = map[int32]string{
		0: "COLLECTOR_STATUS_UNSPECIFIED",
		1: "COLLECTOR_STATUS_OK",
		2: "COLLECTOR_STATUS_FAILED",
		3: "COLLECTOR_STATUS_TIMEOUT",
		4: "COLLECTOR_STATUS_SKIPPED",
		5: "COLLECTOR_STATUS_PARTIAL",
	}
	CollectorStatus_value = map[string]int32{
		"COLLECTOR_STATUS_UNSPECIFIED": 0,
		"COLLECTOR_STATUS_OK":          1,
		"COLLECTOR_STATUS_FAILED":      2,
		"COLLECTOR_STATUS_TIMEOUT":     3,
		"COLLECTOR_STATUS_SKIPPED":     4,
		"COLLECTOR_STATUS_PARTIAL":     5,
	}
)

func (x CollectorStatus) Enum() *CollectorStatus {
	p := new(CollectorStatus)
	*p = x
	return p
}

func (x CollectorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bloodheaven_audit_v1_report_proto_enumTypes[3].Descriptor()
}

func (CollectorStatus) Type() protoreflect.EnumType {
	return &file_bloodheaven_audit_v1_report_proto_enumTypes[3]
}

func (x CollectorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectorStatus.Descriptor instead.
func (CollectorStatus) EnumDescriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{3}
}

// Evidence is how a finding can be reproduced: the exact command or request, and
// what came back from it.
//
// It is published, so it must never contain a secret. Environment variable values,
// key material, passwords in configs and database contents are out of scope at every
// level — only names, presence and sizes are ever read.
type Evidence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is what a reader would run to see the same thing. It is always a real
	// command or a path on disk — never a paraphrase of one.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// output is the answer that was observed: either a fragment of the command's raw
	// output, or a compact rendering of the values parsed out of it. Both are bounded
	// by the producer.
	//
	// A rendering is allowed on purpose. For several observations the raw form carries
	// less than the parsed one — /proc/net/tcp states a listening socket as
	// `0100007F:1F90`, which no reader can check — and the property that matters is
	// that `command` lets them reproduce the observation themselves.
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// truncated says the fragment was cut. Never dropped silently — a shortened
	// capture that does not admit it invites the reader to conclude too much.
	Truncated bool `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// captured_at is RFC3339 UTC.
	CapturedAt    string `protobuf:"bytes,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *Evidence) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Evidence) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Evidence) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *Evidence) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

// Finding is one statement about the audited thing.
//
// Wording rules the producer is expected to have followed: numbers and names rather
// than adjectives, a concrete action in what_to_do rather than "consider reviewing",
// and assumptions spelled out in description.
type Finding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is a stable machine identifier, "<collector>.<what>", e.g. "tls.expired"
	// or "ports.database_exposed". It is what an integration matches on, so it does
	// not change once shipped.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// collector is the check that produced it.
	Collector string   `protobuf:"bytes,2,opt,name=collector,proto3" json:"collector,omitempty"`
	Category  Category `protobuf:"varint,3,opt,name=category,proto3,enum=bloodheaven.audit.v1.Category" json:"category,omitempty"`
	Severity  Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=bloodheaven.audit.v1.Severity" json:"severity,omitempty"`
	// subject is the specific thing the finding is about — a hostname, a port, a
	// record, a container. Empty means the audited target itself.
	Subject      string     `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Title        string     `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description  string     `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	WhyItMatters string     `protobuf:"bytes,8,opt,name=why_it_matters,json=whyItMatters,proto3" json:"why_it_matters,omitempty"`
	WhatToDo     string     `protobuf:"bytes,9,opt,name=what_to_do,json=whatToDo,proto3" json:"what_to_do,omitempty"`
	Confidence   Confidence `protobuf:"varint,10,opt,name=confidence,proto3,enum=bloodheaven.audit.v1.Confidence" json:"confidence,omitempty"`
	// sort_order orders findings within one collector; across collectors the reader
	// sorts by severity first.
	SortOrder int32 `protobuf:"varint,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	// evidence is never empty. A finding that arrives without it is rejected rather
	// than stored, because a claim nobody can check is the one thing this product
	// cannot afford to publish.
	Evidence      []*Evidence `protobuf:"bytes,12,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *Finding) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Finding) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *Finding) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetWhyItMatters() string {
	if x != nil {
		return x.WhyItMatters
	}
	return ""
}

func (x *Finding) GetWhatToDo() string {
	if x != nil {
		return x.WhatToDo
	}
	return ""
}

func (x *Finding) GetConfidence() Confidence {
	if x != nil {
		return x.Confidence
	}
	return Confidence_CONFIDENCE_UNSPECIFIED
}

func (x *Finding) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Finding) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// CollectorResult records what one check did, including doing nothing.
type CollectorResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Collector string                 `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	Status    CollectorStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=bloodheaven.audit.v1.CollectorStatus" json:"status,omitempty"`
	// note is the reader-facing reason for any status other than OK. It says what
	// could not be checked and why, in one plain sentence.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	DurationMs    int32  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorResult) Reset() {
	*x = CollectorResult{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorResult) ProtoMessage() {}

func (x *CollectorResult) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorResult.ProtoReflect.Descriptor instead.
func (*CollectorResult) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *CollectorResult) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (x *CollectorResult) GetStatus() CollectorStatus {
	if x != nil {
		return x.Status
	}
	return CollectorStatus_COLLECTOR_STATUS_UNSPECIFIED
}

func (x *CollectorResult) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CollectorResult) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ChangeItem is one line of "what the deployment will actually do".
//
// This is the section a person shows their own client when asked what they did, so
// it is specific: full paths, exact commands, the ports that will be opened.
type ChangeItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is "file", "command", "firewall_port", "dns_record", "container" or
	// "disk_space".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// target is the thing acted on: a path, a port, a container name.
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// detail is what happens to it.
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeItem) Reset() {
	*x = ChangeItem{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeItem) ProtoMessage() {}

func (x *ChangeItem) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeItem.ProtoReflect.Descriptor instead.
func (*ChangeItem) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChangeItem) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ChangeItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// RollbackItem is one line of the answer to "and how do we undo it".
//
// A deployment with no way back is a finding in its own right; this section is what
// makes that concrete instead of rhetorical.
type RollbackItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind is "snapshot", "image_tag", "proxy_config" or "volume_backup".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// available says whether the thing exists right now. False is the interesting
	// case and the reason this section is not merely instructions.
	Available     bool   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackItem) Reset() {
	*x = RollbackItem{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackItem) ProtoMessage() {}

func (x *RollbackItem) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackItem.ProtoReflect.Descriptor instead.
func (*RollbackItem) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RollbackItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *RollbackItem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Report is one audit, at any level.
type Report struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema_version is checked by the receiver before anything else. An agent built
	// months ago and run today must be told its report is not understood, rather than
	// having it half-read.
	SchemaVersion string `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// level is 0 (passive, contacts nobody), 1 (active, contacts the domain's own
	// servers with its published consent) or 2 (on-server preflight).
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	// domain is set for levels 0 and 1. A level 2 report is about a machine, not a
	// name, and leaves this empty.
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// server_fingerprint identifies the audited machine on level 2. It is a hash of a
	// stable host identifier, never the identifier itself: the report is uploaded, and
	// a machine-id is not ours to publish.
	ServerFingerprint string `protobuf:"bytes,4,opt,name=server_fingerprint,json=serverFingerprint,proto3" json:"server_fingerprint,omitempty"`
	// server_hostname is what the host calls itself, for a human reading the list.
	ServerHostname string `protobuf:"bytes,5,opt,name=server_hostname,json=serverHostname,proto3" json:"server_hostname,omitempty"`
	// generated_at is RFC3339 UTC.
	GeneratedAt string `protobuf:"bytes,6,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// stale_after is when the report stops being presented as current. Server state
	// drifts; the reader is told so rather than left to guess.
	StaleAfter string `protobuf:"bytes,7,opt,name=stale_after,json=staleAfter,proto3" json:"stale_after,omitempty"`
	// producer names what made this report, e.g. "server-audit/0.2.0". It is how a
	// finding is traced back to the code that produced it.
	Producer   string             `protobuf:"bytes,8,opt,name=producer,proto3" json:"producer,omitempty"`
	Findings   []*Finding         `protobuf:"bytes,9,rep,name=findings,proto3" json:"findings,omitempty"`
	Collectors []*CollectorResult `protobuf:"bytes,10,rep,name=collectors,proto3" json:"collectors,omitempty"`
	Changes    []*ChangeItem      `protobuf:"bytes,11,rep,name=changes,proto3" json:"changes,omitempty"`
	Rollback   []*RollbackItem    `protobuf:"bytes,12,rep,name=rollback,proto3" json:"rollback,omitempty"`
	// command_journal is every command the producer actually executed, in order.
	// Level 2 ships it because a client who ran a binary on their production host is
	// owed the full list of what it did, not a summary.
	CommandJournal []string `protobuf:"bytes,13,rep,name=command_journal,json=commandJournal,proto3" json:"command_journal,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_bloodheaven_audit_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_bloodheaven_audit_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *Report) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Report) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Report) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Report) GetServerFingerprint() string {
	if x != nil {
		return x.ServerFingerprint
	}
	return ""
}

func (x *Report) GetServerHostname() string {
	if x != nil {
		return x.ServerHostname
	}
	return ""
}

func (x *Report) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *Report) GetStaleAfter() string {
	if x != nil {
		return x.StaleAfter
	}
	return ""
}

func (x *Report) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Report) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *Report) GetCollectors() []*CollectorResult {
	if x != nil {
		return x.Collectors
	}
	return nil
}

func (x *Report) GetChanges() []*ChangeItem {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *Report) GetRollback() []*RollbackItem {
	if x != nil {
		return x.Rollback
	}
	return nil
}

func (x *Report) GetCommandJournal() []string {
	if x != nil {
		return x.CommandJournal
	}
	return nil
}

var File_bloodheaven_audit_v1_report_proto protoreflect.FileDescriptor

const file_bloodheaven_audit_v1_report_proto_rawDesc = "" +
	"\n" +
	"!bloodheaven/audit/v1/report.proto\x12\x14bloodheaven.audit.v1\"{\n" +
	"\bEvidence\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1f\n" +
	"\vcaptured_at\x18\x04 \x01(\tR\n" +
	"capturedAt\"\xe6\x03\n" +
	"\aFinding\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\tcollector\x18\x02 \x01(\tR\tcollector\x12:\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x1e.bloodheaven.audit.v1.CategoryR\bcategory\x12:\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1e.bloodheaven.audit.v1.SeverityR\bseverity\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12$\n" +
	"\x0ewhy_it_matters\x18\b \x01(\tR\fwhyItMatters\x12\x1c\n" +
	"\n" +
	"what_to_do\x18\t \x01(\tR\bwhatToDo\x12@\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x0e2 .bloodheaven.audit.v1.ConfidenceR\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\x05R\tsortOrder\x12:\n" +
	"\bevidence\x18\f \x03(\v2\x1e.bloodheaven.audit.v1.EvidenceR\bevidence\"\xa3\x01\n" +
	"\x0fCollectorResult\x12\x1c\n" +
	"\tcollector\x18\x01 \x01(\tR\tcollector\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.bloodheaven.audit.v1.CollectorStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\"P\n" +
	"\n" +
	"ChangeItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"X\n" +
	"\fRollbackItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xbc\x04\n" +
	"\x06Report\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12-\n" +
	"\x12server_fingerprint\x18\x04 \x01(\tR\x11serverFingerprint\x12'\n" +
	"\x0fserver_hostname\x18\x05 \x01(\tR\x0eserverHostname\x12!\n" +
	"\fgenerated_at\x18\x06 \x01(\tR\vgeneratedAt\x12\x1f\n" +
	"\vstale_after\x18\a \x01(\tR\n" +
	"staleAfter\x12\x1a\n" +
	"\bproducer\x18\b \x01(\tR\bproducer\x129\n" +
	"\bfindings\x18\t \x03(\v2\x1d.bloodheaven.audit.v1.FindingR\bfindings\x12E\n" +
	"\n" +
	"collectors\x18\n" +
	" \x03(\v2%.bloodheaven.audit.v1.CollectorResultR\n" +
	"collectors\x12:\n" +
	"\achanges\x18\v \x03(\v2 .bloodheaven.audit.v1.ChangeItemR\achanges\x12>\n" +
	"\brollback\x18\f \x03(\v2\".bloodheaven.audit.v1.RollbackItemR\brollback\x12'\n" +
	"\x0fcommand_journal\x18\r \x03(\tR\x0ecommandJournal*c\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x14\n" +
	"\x10SEVERITY_BLOCKER\x10\x03*\x94\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CATEGORY_CONFLICT\x10\x01\x12\x15\n" +
	"\x11CATEGORY_RESOURCE\x10\x02\x12\x15\n" +
	"\x11CATEGORY_SECURITY\x10\x03\x12\x13\n" +
	"\x0fCATEGORY_EXPIRY\x10\x04\x12\x14\n" +
	"\x10CATEGORY_MISSING\x10\x05*h\n" +
	"\n" +
	"Confidence\x12\x1a\n" +
	"\x16CONFIDENCE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCONFIDENCE_LOW\x10\x01\x12\x15\n" +
	"\x11CONFIDENCE_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fCONFIDENCE_HIGH\x10\x03*\xc3\x01\n" +
	"\x0fCollectorStatus\x12 \n" +
	"\x1cCOLLECTOR_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COLLECTOR_STATUS_OK\x10\x01\x12\x1b\n" +
	"\x17COLLECTOR_STATUS_FAILED\x10\x02\x12\x1c\n" +
	"\x18COLLECTOR_STATUS_TIMEOUT\x10\x03\x12\x1c\n" +
	"\x18COLLECTOR_STATUS_SKIPPED\x10\x04\x12\x1c\n" +
	"\x18COLLECTOR_STATUS_PARTIAL\x10\x05BMZKgithub.com/BloodHeavenDevelop/contracts/gen/go/bloodheaven/audit/v1;auditv1b\x06proto3"

var (
	file_bloodheaven_audit_v1_report_proto_rawDescOnce sync.Once
	file_bloodheaven_audit_v1_report_proto_rawDescData []byte
)

func file_bloodheaven_audit_v1_report_proto_rawDescGZIP() []byte {
	file_bloodheaven_audit_v1_report_proto_rawDescOnce.Do(func() {
		file_bloodheaven_audit_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bloodheaven_audit_v1_report_proto_rawDesc), len(file_bloodheaven_audit_v1_report_proto_rawDesc)))
	})
	return file_bloodheaven_audit_v1_report_proto_rawDescData
}

var file_bloodheaven_audit_v1_report_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bloodheaven_audit_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bloodheaven_audit_v1_report_proto_goTypes = []any{
	(Severity)(0),           // 0: bloodheaven.audit.v1.Severity
	(Category)(0),           // 1: bloodheaven.audit.v1.Category
	(Confidence)(0),         // 2: bloodheaven.audit.v1.Confidence
	(CollectorStatus)(0),    // 3: bloodheaven.audit.v1.CollectorStatus
	(*Evidence)(nil),        // 4: bloodheaven.audit.v1.Evidence
	(*Finding)(nil),         // 5: bloodheaven.audit.v1.Finding
	(*CollectorResult)(nil), // 6: bloodheaven.audit.v1.CollectorResult
	(*ChangeItem)(nil),      // 7: bloodheaven.audit.v1.ChangeItem
	(*RollbackItem)(nil),    // 8: bloodheaven.audit.v1.RollbackItem
	(*Report)(nil),          // 9: bloodheaven.audit.v1.Report
}
var file_bloodheaven_audit_v1_report_proto_depIdxs = []int32{
	1, // 0: bloodheaven.audit.v1.Finding.category:type_name -> bloodheaven.audit.v1.Category
	0, // 1: bloodheaven.audit.v1.Finding.severity:type_name -> bloodheaven.audit.v1.Severity
	2, // 2: bloodheaven.audit.v1.Finding.confidence:type_name -> bloodheaven.audit.v1.Confidence
	4, // 3: bloodheaven.audit.v1.Finding.evidence:type_name -> bloodheaven.audit.v1.Evidence
	3, // 4: bloodheaven.audit.v1.CollectorResult.status:type_name -> bloodheaven.audit.v1.CollectorStatus
	5, // 5: bloodheaven.audit.v1.Report.findings:type_name -> bloodheaven.audit.v1.Finding
	6, // 6: bloodheaven.audit.v1.Report.collectors:type_name -> bloodheaven.audit.v1.CollectorResult
	7, // 7: bloodheaven.audit.v1.Report.changes:type_name -> bloodheaven.audit.v1.ChangeItem
	8, // 8: bloodheaven.audit.v1.Report.rollback:type_name -> bloodheaven.audit.v1.RollbackItem
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_bloodheaven_audit_v1_report_proto_init() }
func file_bloodheaven_audit_v1_report_proto_init() {
	if File_bloodheaven_audit_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bloodheaven_audit_v1_report_proto_rawDesc), len(file_bloodheaven_audit_v1_report_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bloodheaven_audit_v1_report_proto_goTypes,
		DependencyIndexes: file_bloodheaven_audit_v1_report_proto_depIdxs,
		EnumInfos:         file_bloodheaven_audit_v1_report_proto_enumTypes,
		MessageInfos:      file_bloodheaven_audit_v1_report_proto_msgTypes,
	}.Build()
	File_bloodheaven_audit_v1_report_proto = out.File
	file_bloodheaven_audit_v1_report_proto_goTypes = nil
	file_bloodheaven_audit_v1_report_proto_depIdxs = nil
}
